USDA.ARS.GRIN.Admin.WebUI/USDA.ARS.GRIN.Admin.WebUI/ViewModels/SiteManagement/CGC/CGCDocumentEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace USDA.ARS.GRIN.Admin.WebUI.ViewModels.SiteManagement
{
    public class CGCDocumentEditViewModel: BaseViewModel
    {
    }
}

USDA.ARS.GRIN.Admin.WebUI/USDA.ARS.GRIN.Admin.WebUI/ViewModels/SiteManagement/CGC/CGCDocumentSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace USDA.ARS.GRIN.Admin.WebUI.ViewModels.SiteManagement
{
    public class CGCDocumentSearchViewModel: BaseSearchViewModel
    {
    }
}

USDA.ARS.GRIN.Admin.WebUI/USDA.ARS.GRIN.Admin.WebUI/Controllers/SiteManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Admin.WebUI.ViewModels;
using USDA.ARS.GRIN.Admin.WebUI.ViewModels.SiteManagement;
using USDA.ARS.GRIN.Admin.Models;
using USDA.ARS.GRIN.Admin.Service;

namespace USDA.ARS.GRIN.Admin.WebUI.Controllers
{
    public class SiteManagementController : Controller
    {
        const string BASE_PATH = "~/Views/SiteManagement/";
        // GET: SiteManagement
        public ActionResult Index()
        {
            // TEMP: Replace with app home page once functionality is designed (CBH, 4/11/2021)
            return RedirectToAction("CGC");
        }

        public ActionResult CGC()
        {
            SiteManagementHomeViewModel siteManagementHomeViewModel = new SiteManagementHomeViewModel();
            TempData["page_title"] = "CGC Content";
            return View(BASE_PATH + "CGC/Index.cshtml",siteManagementHomeViewModel);
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public PartialViewResult CGCDocumentListRecent()
        {
            CGCDocumentSearchViewModel viewModel = new CGCDocumentSearchViewModel();
            SiteManagementService siteManagementService = new SiteManagementService();

            try
            {
                //viewModel.CWRMaps = _taxonomyService.FindRecentCWRMaps();
                return PartialView(BASE_PATH + "/CGC/_SearchResults.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                return PartialView("~/Views/Error/_Error.cshtml", viewModel);
            }
        }
    }
}

USDA.ARS.GRIN.Admin.WebUI/USDA.ARS.GRIN.Admin.WebUI/Views/SiteManagement/CGC/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ============================================================================================== -->
<!-- TABBED VIEW -->
<!-- ============================================================================================== -->
<div class="box box-primary" style="padding:10px;">
    <div class="box-header with-border">
        <h3 class="box-title">CGC Documents</h3>

        <div class="box-tools pull-right">
            <div class="has-feedback">
            </div>
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active" style="background-color:#ebebeb;">
                    <a href="#tab_recent" id="tab-recently-added" title="CGCDocumentListRecent" class="selector-tab" data-toggle="tab" aria-expanded="true">Recently Modified</a>
                </li>
                <li class="" style="background-color:#ebebeb;">
                    <a href="#tab_search" id="tab-search" title="" class="selector-tab" data-toggle="tab" aria-expanded="false">
                        <i class="fa fa-search"></i>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_recent">
                    <div id="section-recently-added">
                    </div>
                </div>
                <div class="tab-pane" id="tab_search">
                    <div id="section-search-results">
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>

<script>

     $(".selector-tab").click(function () {
        var id = $(this).attr('id');
        var action = $(this).attr('title');
        var link = '@Url.Action("Action", "SiteManagement")';
        var displaySection = '';

        // Clear any checked items.
        $('.mailbox-messages input:checkbox').prop('checked', false);

        if (action != '') {
            displaySection = "#" + id.replace("tab", "section");
            link = link.replace("Action", action);

            //DEBUG
            alert(displaySection + ", " + link);

            $(displaySection).load(link);
            InitializeDataTable();
        }
    });

    function DisplayRecent()
    {
        var link = '@Url.Action("CGCDocumentListRecent", "SiteManagement")';
        $.ajax(
            {
                type: 'POST',
                url: link,
                success:
                    function (response) {
                        $("#section-recent").html(response);
                    },
                error:
                    function (response) {
                        console.log(response);
                    }
            });
    }

    function InitializeDataTable() {
        $(document).ready(function () {
            $('table.ggtools').DataTable({
                'destroy': true,
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            });
            //}
        });
    }
</script>

USDA.ARS.GRIN.Admin.WebUI/USDA.ARS.GRIN.Admin.WebUI/Views/SiteManagement/CGC/_SearchResults.cshtml
@model USDA.ARS.GRIN.Admin.WebUI.ViewModels.SiteManagement.CGCDocumentSearchViewModel 
<div style="margin-top:15px;">
    <div class="mailbox-controls">
        <button type="button" class="btn btn-success btn-sm check-all-search-results">
            <i class="fa fa-check"></i>
        </button>
        <button type="button" class="btn btn-danger btn-sm uncheck-all-search-results">
            <i class="fa fa-check-circle-o"></i>
        </button>
        <button type="button" class="btn btn-primary btn-sm">
            <i class="fa fa-document"></i>Add New Document
        </button>
        <div class="pull-right">
            <button type="button" disabled class="btn btn-default btn-sm">
                Export
            </button>
        </div>
    </div>
    <div class="table-responsive mailbox-messages">
        <h2>TEST</h2>
    </div>
</div>